name: MurderMystery
version: 2.0
api: 3.x.x
author: Dantedevs
main: mm\MurderMystery
description: A PMMP MINIGAME MURDERMYSTERY

commands:
  murdermystery:
    description: "MurderMysteryCMDS By DanteDevs"
    aliases: [mm, mrd, murder]
