## CREDITS TO LEYKEY
Prefix: §l§cMM:
#
# Speed of gold spawning (sec)
GoldSpawnRate: 3
#
# Gold spawns
GoldSpawns: 3
#
# Waiting status
WaitingStatus: §cWaiting for more players...
#
# Starting status
StartingStatus: Starting in {sec}s
#
# The scoreboard that gets displayed to players in the waiting lobby
LobbyScoreboard: 
- "§7§r"
- "§fPlayers: §a{players}/16"
- "§r"
- "starting in: {startt}"
- "§r§7"
- "§fMap: §a{map}"
- "§b"
- "§eplay.yourserver.net"
GameScoreboard:
- "§7§r"
- "§fRole: §a{role}"
- "§r"
- "§fInnocents left: §a{innocents}"
- "§fTime Left: §a{gamet}"
- "§a§r"
- "§fDetective: §a{detec_status}"
- "§r§7"
- "§fMap: §a{map}"
- "§b"
- "§eplay.yourserver.net"
#
# The scoreboard that gets displayed to players after a game
RestartScoreboard:
- "§7§r"
- "§fRole: §aSpectator"
- "§r"
- "§fInnocents left: §a0"
- "§fTime Left: §a0"
- "§a§r"
- "§fDetective: §a{detec_status}"
- "§r§7"
- "§fMap: §a{map}"
- "§b"
- "§eplay.yourserver.net"
